spring:
  application:
    name: validator


management:
  endpoint:
    shutdown:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"

server:
  error:
    whitelabel:
      enabled: false  # Disable the default error response page
    include-message: always
    include-binding-errors: always


broker:
  url: ${BROKER_URL:tcp://localhost:61616}
  username: admin
  password: admin


orders:
  topic: orders.topic
  log: /app/var/log/order-generator.log

heartbeat:
  topic: heartbeat.topic
  log: /app/var/log/heartbeat.log


validator:
  output:
    report:
      template: /html/report.vm




tests:
  termination:
    timeout: 40000
    shutdown-on-success: true
  jms-connect:
    - order-generator
    - heartbeat
  log-validation:
    heartbeat:
      - "HEARTBEAT .* Sent heartbeat message.*"
    orders:
      - ".*ORDERS .* Received event: CONSUMER_CREATED for name: heartbeat.*"
      - ".*ORDERS .* Heartbeat sequence.*"
