spring:
  application:
    name: validator


management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"

server:
  error:
    whitelabel:
      enabled: false  # Disable the default error response page
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.web: TRACE  # Log errors from Spring MVC at ERROR level

broker:
  url: ${BROKER_URL:tcp://localhost:61616}
  username: admin
  password: admin


orders:
  topic: orders.topic
  log: /app/var/log/orders.log

heartbeat:
  topic: heartbeat.topic
  log: /app/var/log/heartbeat.log


validator:
  output:
    report:
      template: /html/report.vm




tests:
  jms-connect:
     - orders
     - heartbeat
  log-validation:
    orders:
      - "Send order: [\\.]"
      - "Received order: [\\.]"
      - "Heartbeat received"
