spring:
  application:
    name: validator


management:
  endpoint:
    shutdown:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"

server:
  error:
    whitelabel:
      enabled: false  # Disable the default error response page
    include-message: always
    include-binding-errors: always


broker:
  url: ${BROKER_URL:tcp://localhost:61616}
  username: admin
  password: admin


orders-generator:
  topic: orders.topic
  log: /app/var/log/order-generator.log

orders-client:
  topic: orders.topic
  log: /app/var/log/order-client.log

heartbeat:
  topic: heartbeat.topic
  log: /app/var/log/heartbeat.log


validator:
  output:
    report:
      template: /html/report.vm




tests:
  termination:
    timeout: 15000  # in milliseconds
    shutdown-on-success: true
  jms-connect:
    - order-generator
    - heartbeat
    - order-client
  log-validation:
    heartbeat:
      - "HEARTBEAT .* Sent heartbeat message.*"
      - "ORDR_GEN .* Heartbeat sequence.*"
      - "ORDR_CLN .* Heartbeat sequence.*"
    orders:
      - ".*ORDR_GEN .* Received event: CONSUMER_CREATED for name: heartbeat.*"
      - ".*ORDR_GEN .* Sent order: .*"
    initialized:
      - "OrderProducer initialized"
      - "HeartbeatProducer initialized"
