services:
  validator:
    build:
      context: ./validator
      dockerfile: Dockerfile
    container_name: validator
    networks:
      - autoqa
    environment:
      BROKER_URL: "tcp://broker:61616"
      BROKER_USERNAME: artemis
      BROKER_PASSWORD: artemis
      LOG_FILE: "/app/var/log/validator.log"
      LOG_LEVEL: "INFO"
    ports:
      - "5005:5005"
      - "8081:8080"
    volumes:
      - logs:/app/var/log
      - ./reports:/app/var/reports


  order-client:
    build:
      context: ./order-client
      dockerfile: Dockerfile
    container_name: order-client
    networks:
      - autoqa
    depends_on:
      validator:
        condition: service_healthy
      heartbeat:
        condition: service_healthy
    environment:
      BROKER_URL: "tcp://broker:61616"
      BROKER_USERNAME: artemis
      BROKER_PASSWORD: artemis
      LOG_FILE: "/app/var/log/order-client.log"
      LOG_LEVEL: "INFO"
      CLASSPATH: "/app/classes:/app/resources"
      CFG_TOPIC: properties
    ports:
      - "5008:5005"
      - "8084:8080"
    volumes:
      - logs:/app/var/log

  order-generator:
    build:
      context: ./order-generator
      dockerfile: Dockerfile
    container_name: order-generator
    networks:
      - autoqa
    depends_on:
      validator:
        condition: service_healthy
      heartbeat:
        condition: service_healthy
      order-client:
        condition: service_healthy
    environment:
      BROKER_URL: "tcp://broker:61616"
      BROKER_USERNAME: artemis
      BROKER_PASSWORD: artemis
      LOG_FILE: "/app/var/log/order-generator.log"
      LOG_LEVEL: "INFO"
      CLASSPATH: "/app/classes:/app/resources"
      CFG_TOPIC: properties
    ports:
      - "5007:5005"
      - "8083:8080"
    volumes:
      - logs:/app/var/log


  heartbeat:
    build:
      context: ./heartbeat
      dockerfile: Dockerfile
    container_name: heartbeat
    networks:
      - autoqa
    depends_on:
      validator:
        condition: service_healthy
    environment:
      BROKER_URL: "tcp://broker:61616"
      BROKER_USERNAME: artemis
      BROKER_PASSWORD: artemis
      LOG_FILE: "/app/var/log/heartbeat.log"
      LOG_LEVEL: "INFO"
      CFG_TOPIC: com.kagr.config
    ports:
      - "5006:5005"
      - "8082:8080"
    volumes:
      - ../reports:/app/var/reports
      - logs:/app/var/log





volumes:
  logs:
    driver: local
    driver_opts:
      type: 'tmpfs'
      device: 'tmpfs'

networks:
  autoqa:
    external: true
