services:
  broker:
    image: apache/activemq-artemis:latest
    container_name: broker
    networks:
      - autoqa
    ports:
      - "61616:61616"  # JMS
      - "8161:8161"    # Web console
      - "1099:1099"    # JMX
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
      ARTEMIS_ALLOW_ANONYMOUS: "true"
    volumes:
      - ./config/broker.xml:/var/lib/artemis-instance/etc-override/broker.xml:ro
      - ./config/artemis-users.properties:/var/lib/artemis-instance/etc-override/artemis-users.properties:ro
      - ./config/artemis-roles.properties:/var/lib/artemis-instance/etc-override/artemis-roles.properties:ro

networks:
  autoqa:
    external: true
