services:
  validator:
    image: validator:latest
    container_name: validator
    networks:
      - autoqa
    environment:
      BROKER_URL: "tcp://broker:61616"
      BROKER_USERNAME: artemis
      BROKER_PASSWORD: artemis
      LOG_FILE: "/app/var/log/validator.log"
      LOG_LEVEL: "INFO"
    ports:
      - "5005:5005"
      - "8081:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - logs:/app/var/log
      - ../validator/target/classes/:/app/target/classes/:ro
      - ../validator/src/main/resources/logback.xml:/app/resources/logback.xml:ro



  heartbeat:
    image: heartbeat:latest
    container_name: heartbeat
    networks:
      - autoqa
    depends_on:
      validator:
        condition: service_healthy
    environment:
      BROKER_URL: "tcp://broker:61616"
      BROKER_USERNAME: artemis
      BROKER_PASSWORD: artemis
      LOG_FILE: "/app/var/log/heartbeat.log"
      LOG_LEVEL: "INFO"
    ports:
      - "5006:5005"
      - "8082:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 5s
      timeout: 10s
      retries: 3
    volumes:
      - logs:/app/var/log



  orders:
    image: order-generator:latest
    container_name: order-generator
    networks:
      - autoqa
    depends_on:
      validator:
        condition: service_healthy
    environment:
      BROKER_URL: "tcp://broker:61616"
      BROKER_USERNAME: artemis
      BROKER_PASSWORD: artemis
      LOG_FILE: "/app/var/log/order-generator.log"
      LOG_LEVEL: "INFO"
      CLASSPATH: "/app/classes:/app/resources"
    ports:
      - "5007:5005"
      - "8083:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 5s
      timeout: 10s
      retries: 3
    volumes:
      - logs:/app/var/log
      - ../order-generator/target/classes/:/app/target/classes/:ro
      - ../order-generator/src/main/resources/logback.xml:/app/resources/logback.xml:ro


volumes:
  logs:
    driver: local
    driver_opts:
      type: 'tmpfs'
      device: 'tmpfs'

networks:
  autoqa:
    external: true
